compatibility_date = "2021-10-18"
name = "mastercard-backbank-dev"
type = "javascript" # webpack
account_id = "9ddca7c9df604668fc6d14f079b2f066"
workers_dev = true #if using default subdomain, here: api ok
# wasm_modules={BACKBANK_WASM="./a.out.wasm"}# "./src/glue"}
# webpack_config = "webpack.config.js"
route = "" #if not using default subdomain, here: api not needed, defaults err
zone_id = "" #if not using default subdomain, here: api not needed
# [site]
# bucket = "./dist"
# entry-point = "workers-site"
kv_namespaces = [
  {binding="backbank",id="e4609a2b6fa943aab9e44185293dae3a"}
]

[env.production]
# exclude = ["node_modules","*"]
# include = ["dist/*","src/*"]
name = "mastercard-backbank"

[env.staging]
name = "mastercard-backbank-staging"

[durable_objects]
bindings = [{ name = "EXAMPLE_CLASS_DURABLE_OBJECT", class_name = "DurableObjectExample" }]
# ,{ name = "REQUIRE_CLASS_DURABLE_OBJECT", class_name = "Require" }

[env.staging.durable_objects]
bindings = [{ name = "EXAMPLE_CLASS_DURABLE_OBJECT", class_name = "DurableObjectExample" }]

[env.production.durable_objects]
bindings = [{ name = "EXAMPLE_CLASS_DURABLE_OBJECT", class_name = "DurableObjectExample" }]

[env.preview.durable_objects]
bindings = [{ name = "EXAMPLE_CLASS_DURABLE_OBJECT", class_name = "DurableObjectExample" }]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["DurableObjectExample"]

[[migrations]]
tag = "v2"
new_classes = ["Require"]

[[migrations]]
tag = "v3"
deleted_classes = ["Require"]

[vars]
WORKERS_RS_VERSION = "0.0.9"
[build.upload]
format = "modules" # "service-workers"
dir = "build/worker" # dist for libraries...
main = "./shim.mjs"

[build]
command = "worker-build --release" 
# https://github.com/NickCarducci/mastercard-backbank/blob/main/wrangler.toml

#[miniflare]
#global_async_io = true 

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
